admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /backoffice

_sonata_admin:
    resource: .
    type: sonata_admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Routes for app bundles
backoffice:
    resource: "@BackofficeBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
