admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /backoffice

_sonata_admin:
    resource: .
    type: sonata_admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Routes for app bundles
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
